// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thallo.Data;

#nullable disable

namespace Thallo.Migrations
{
    [DbContext(typeof(ThalloContext))]
    [Migration("20260616155332_AddDailyHealth")]
    partial class AddDailyHealth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Thallo.Models.DailyHealth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvgHr")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvgSpo2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvgStress")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxHr")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinHr")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RestingHr")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SleepAwake")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SleepDeep")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SleepEnd")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SleepLight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SleepRem")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SleepStart")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SleepTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Steps")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DailyHealth");
                });

            modelBuilder.Entity("Thallo.Models.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Calories")
                        .HasColumnType("REAL");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Protein")
                        .HasColumnType("REAL");

                    b.Property<double?>("Salt")
                        .HasColumnType("REAL");

                    b.Property<double?>("Sugar")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Thallo.Models.Shortcut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aggregation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowTally")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Shortcuts");
                });
#pragma warning restore 612, 618
        }
    }
}
